<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Composer\\CustomDirectoryInstaller' => array($vendorDir . '/idct/composer-custom-directory/src'),
);
