<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'c14057a02afc95b84dc5bf85d98c5b66' => $baseDir . '/admin/includes/lib/Wp-dismissible-notices-handler/handler.php',
    'e7a23b473708f4b0fb5b99fe921bee83' => $baseDir . '/public/includes/lib/Widgets-helper/wph-widget.php',
    '9b6589aa6a8382a7459438252aee60ae' => $baseDir . '/includes/lib/Fakepage/fake-page.php',
    '1fa8862ea6a31004f198b1e9b7b6b499' => $baseDir . '/includes/lib/Template/template.php',
    '33463dafc79559dfcabd4bb559eb4b57' => $baseDir . '/admin/includes/lib/Cpt_columns/CPT_Columns.php',
    '5883ee4b643b7e87de56323bec06b24c' => $baseDir . '/includes/lib/Language/language.php',
    'ce20db008ec08ec1de765a16020c5985' => $baseDir . '/includes/lib/Cpt-core/CPT_Core.php',
    '9c9ba5b7922c4da6a6ffadd6544d169a' => $baseDir . '/includes/lib/Taxonomy_core/Taxonomy_Core.php',
    'a50f2d2ba04e0c6b552331bf2bdeba41' => $baseDir . '/admin/includes/lib/Wp-review-me/review.php',
    '8585965b6d416e38b2582f2efe0c6909' => $baseDir . '/admin/includes/lib/Cmb2/init.php',
);
